#!/usr/bin/python


title_var_dic = {
    # Repeated titles are omitted as they are associated to the same variable
    # Recall var_ncdm will be a list title var_ncdm[N]
    # Background titles
    '(.)p_scf': 'p_scf',
    '(.)p_smg': 'p_smg',
    '(.)rho_b': 'rho_b',
    '(.)rho_cdm': 'rho_cdm',
    '(.)rho_crit': 'rho_crit',
    '(.)rho_dcdm': 'rho_dcdm',
    '(.)rho_dcm': 'rho_dr',
    '(.)rho_fld': 'rho_fld',
    '(.)rho_g': 'rho_g',
    '(.)rho_lambda': 'rho_lambda',
    '(.)rho_ncdm': 'rho_ncdm',
    '(.)rho_scf': 'rho_scf',
    '(.)rho_smg': 'rho_smg',
    '(.)rho_ur': 'rho_ur',
    'G_field_smg': 'G_field_smg',
    'G_phi_smg': 'G_phi_smg',
    'G_psi_smg': 'G_psi_smg',
    'H [1/Mpc]': 'H',
    'M*^2_smg': 'M2_smg',
    'Mpl_running_smg': 'mpl_running_smg',
    "V''_scf": 'ddV_scf',
    "V'_scf": 'dV_scf',
    'V_scf': 'V_scf',
    'alpha_4_smg': 'alpha_4_smg',
    'alpha_4_prime_smg': 'alpha_4_prime_smg',
    'alpha_5_prime_smg': 'alpha_5_prime_smg',
    'alpha_5_smg': 'alpha_5_smg',
    'ang.diam.dist.': 'ang_distance',
    'braiding_prime_smg [Mpc^-1]': 'braiding_prime_smg',
    'braiding_smg': 'braiding_smg',
    'c_s^2': 'cs2_smg',
    'comov. dist.': 'conf_distance',
    'comov.snd.hrz.': 'rs',
    'conf. time [Mpc]': 'tau',
    'gamma_1': 'gamma_1_smg',
    'gamma_2': 'gamma_2_smg',
    'gamma_3': 'gamma_3_smg',
    'gr.fac. D': 'D',
    'gr.fac. f': 'f',
    'kin (D)': 'kinetic_D_smg',
    'kineticity_prime_smg [Mpc^-1]': 'kineticity_prime_smg',
    'kineticity_smg': 'kineticity_smg',
    'lambda_1': 'lambda_1_smg',
    'lambda_2': 'lambda_2_smg',
    'lambda_3': 'lambda_3_smg',
    'lambda_4': 'lambda_4_smg',
    'lambda_5': 'lambda_5_smg',
    'lambda_6': 'lambda_6_smg',
    'lambda_7': 'lambda_7_smg',
    'lambda_8': 'lambda_8_smg',
    'lum. dist.': 'lum_distance',
    "phi'": 'phi_prime_smg',
    "phi''": 'phi_prime_prime',
    "phi'_scf": 'phi_prime_scf',
    'phi_scf': 'phi_scf',
    'phi_smg': 'phi_smg',
    'proper time [Gyr]': 't',
    'tensor_excess_smg': 'tensor_excess_smg',
    'z': 'z',
    # Thermodynamic titles
    'Tb [K]': 'Tb',
    'c_b^2': 'cb2',
    'exp(-kappa)': 'exp_m_kappa',
    'g [Mpc^-1]': 'g',
    "g'": 'dg',
    "g''": 'ddg',
    "kappa' [Mpc^-1]": 'dkappa',
    "kappa''": 'ddkappa',
    "kappa'''": 'dddkappa',
    'max.rate': 'rate',
    'tau_d': 'tau_d',
    'x_e': 'xe',
    # Scalar perturbation titles
    'V_x_prime_smg': 'V_x_prime_smg',
    'V_x_smg': 'V_x_smg',
    'a': 'a',
    'alpha': 'alpha',
    'delta_Tb': 'delta_temp',
    'delta_b': 'delta_b',
    'delta_cdm': 'delta_cdm',
    'delta_ncdm': 'delta_ncdm',
    'delta_chi': 'delta_chi',
    'delta_dcdm': 'delta_dcdm',
    'delta_dr': 'delta_dr',
    'delta_g': 'delta_g',
    'delta_scf': 'delta_scf',
    'delta_ur': 'delta_ur',
    'eta': 'eta_sync',
    'phi': 'phi',
    'pol0_g': 'pol0_g',
    'pol1_g': 'pol1_g',
    'pol2_g': 'pol2_g',
    'psi': 'psi',
    'shear_dr': 'shear_dr',
    'shear_g': 'shear_g',
    'shear_ur': 'shear_ur',
    'shear_ncdm': 'shear_ncdm',
    'tau [Mpc]': 'tau',
    'theta_b': 'theta_b',
    'theta_cdm': 'theta_cdm',
    'theta_ncdm': 'theta_ncdm',
    'theta_dcdm': 'theta_dcdm',
    'theta_dr': 'theta_dr',
    'theta_g': 'theta_g',
    'theta_scf': 'theta_scf',
    'theta_ur': 'theta_ur',
    # Tensorial perturbation titles
    'H (gw)': 'gw',
    'Hdot (gwdot)': 'gwdot',
    'l4_g': 'l4_g',
    'l4_ur': 'l4_ur',
    'pol4_g': 'pol4_g',
    # Primordial titles
    'P_scalar(k)': 'pm_pks',  # Variable name is NOT from source
    'P_tensor(k)': 'pm_pkt',  # Variable name is NOT from source
    'k [1/Mpc]': 'k',
    # Spectra titles
    '-T_b/k2': 'camb_T_b',
    '-T_cdm/k2': 'camb_T_cdm',
    '-T_g/k2': 'camb_T_g',
    '-T_ncdm/k2': 'camb_T_ncdm',
    '-T_tot/k2': 'camb_T_tot',
    'd_b': 'delta_b',
    'd_cdm': 'delta_cdm',
    'd_ncdm': 'delta_ncdm',
    'd_dcdm': 'delta_dcdm',
    'd_dr': 'delta_dr',
    'd_fld': 'delta_fld',
    'd_g': 'delta_g',
    'd_scf': 'delta_scf',
    'd_tot': 'delta_tot',
    'k (h/Mpc)': 'k_over_h',
    't__scf': 'theta_scf',
    't_b': 'theta_b',
    't_cdm': 'theta_cdm',
    't_ncdm': 'theta_ncdm',
    't_dr': 'theta_dr',
    't_fld': 'theta_fld',
    't_g': 'theta_g',
    't_tot': 'theta_tot',
    't_ur': 'theta_ur',
    # Output pk* titles
    'P (Mpc/h)^3': 'pk',
    # Output cl* titles
    'l': 'l',  # See var
    'TT': 'tt',
    'EE': 'ee',
    'TE': 'te',
    'BB': 'BB',
    'phiphi': 'pp',
    'TPhi': 'tp',
    'Ephi': 'ep',
    'dd': 'camb_dd',
    'dT': 'camb_dt',
    'dE': 'camb_de',
    # Recall that 'dens[N]-dens[M]'
    'dens-dens': 'd_d',  # d_d[N][M],
    # Recall that 'T-dens[N]' and 'phi-dens[N]'
    'T-dens': 't_d',
    'phi-dens': 'p_d',
    # Recall that 'lens[N]-lens[M]'
    'lens-lens': 'l_l',  # l_l[N][M],
    # Recall that T-lens[N]
    'T-lens': 't_l',
    # Recall that 'dens[N]-lens[M]'
    'dens-lens': 'd_l'  # d_l[N][M]
}

var_title_dic = {var: title for title, var in title_var_dic.iteritems()}
